import { logger } from '../services/logger.js';
import { Octokit } from '@octokit/rest';

export async function openPullRequest(issueKey, plan, validationPassed, patch, githubConfig) {
  logger.info({ issueKey }, 'PR Agent activated');

  const token = githubConfig?.token || process.env.GITHUB_TOKEN;
  const owner = githubConfig?.owner || process.env.GITHUB_OWNER;
  const repo = githubConfig?.repo || process.env.GITHUB_REPO;

  if (!token || !owner || !repo || token === 'your_personal_access_token') {
    logger.warn('GitHub credentials (GITHUB_TOKEN, GITHUB_OWNER, GITHUB_REPO) missing or default. Mocking PR creation.');
    const mockUrl = `https://github.com/mock-org/mock-repo/pull/${Math.floor(Math.random() * 1000)}`;
    logger.info({ issueKey, url: mockUrl }, 'Mock PR opened successfully');
    return mockUrl;
  }

  const octokit = new Octokit({ auth: token });
  const branchName = `jira/${issueKey.toLowerCase()}-${Date.now()}`;

  try {
    // 1. Get default branch dynamically from repo metadata
    const repoData = await octokit.rest.repos.get({ owner, repo });
    const defaultBranch = repoData.data.default_branch || 'main';
    
    let baseRef = await octokit.rest.git.getRef({ owner, repo, ref: `heads/${defaultBranch}` });
    const baseCommitSha = baseRef.data.object.sha;

    // 2. Get the base commit tree
    const baseCommit = await octokit.rest.git.getCommit({ owner, repo, commit_sha: baseCommitSha });
    const baseTreeSha = baseCommit.data.tree.sha;

    // 3. Create blobs for all patched files
    const newTreeItems = await Promise.all(patch.patches.map(async (p) => {
      const blob = await octokit.rest.git.createBlob({
        owner,
        repo,
        content: p.newContent,
        encoding: 'utf-8'
      });
      return {
        path: p.filePath,
        mode: '100644',
        type: 'blob',
        sha: blob.data.sha
      };
    }));

    // 4. Create a new tree
    const newTree = await octokit.rest.git.createTree({
      owner,
      repo,
      base_tree: baseTreeSha,
      tree: newTreeItems
    });

    // 5. Create a new commit
    const newCommit = await octokit.rest.git.createCommit({
      owner,
      repo,
      message: `Fixes ${issueKey}: ${plan.summary.substring(0, 50)}...`,
      tree: newTree.data.sha,
      parents: [baseCommitSha]
    });

    // 6. Create the new branch reference
    await octokit.rest.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${branchName}`,
      sha: newCommit.data.sha
    });

    // 7. Open the Pull Request
    const prDescription = `
## Resolves ${issueKey}

### Summary
${plan.summary}

### Validation
${validationPassed ? '✅ Passed all tests' : '⚠️ Validation failed - proceed with caution'}

*This PR was auto-generated by the AI Agent.*
    `.trim();

    const pr = await octokit.rest.pulls.create({
      owner,
      repo,
      title: `[${issueKey}] AI Auto-fix`,
      head: branchName,
      base: baseRef.data.ref.replace('refs/heads/', ''),
      body: prDescription
    });

    logger.info({ issueKey, prUrl: pr.data.html_url }, 'GitHub PR created successfully');
    return pr.data.html_url;

  } catch (error) {
    logger.error({ error: error.message, issueKey }, 'Failed to create GitHub PR');
    throw error;
  }
}
